-- 코드를 입력하세요
SELECT ri.FOOD_TYPE, ri.REST_ID, ri.REST_NAME, ri.FAVORITES
FROM REST_INFO ri
JOIN (
    SELECT
        FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) m
ON ri.FOOD_TYPE = m.FOOD_TYPE
AND ri.FAVORITES = m.MAX_FAVORITES
ORDER BY ri.FOOD_TYPE DESC;
