-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) '전체주소' , INSERT(INSERT(u.TLNO, 4, 0, '-'), 9, 0, '-') '전화번호'
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
GROUP BY u.USER_ID, u.NICKNAME, u.CITY, u.STREET_ADDRESS1, u.STREET_ADDRESS2, u.TLNO
HAVING COUNT(b.BOARD_ID) >= 3
ORDER BY USER_ID DESC;