-- 코드를 입력하세요
SELECT ri.REST_ID AS REST_ID, ri.REST_NAME AS REST_NAME, ri.FOOD_TYPE AS FOOD_TYPE, ri.FAVORITES AS FAVORITES, ri.ADDRESS AS ADDRESS, ROUND(AVG(rr.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO ri JOIN REST_REVIEW rr ON ri.REST_ID = rr.REST_ID
WHERE ri.ADDRESS LIKE '서울%'
GROUP BY ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE
ORDER BY SCORE DESC, ri.FAVORITES DESC