-- 코드를 입력하세요
SELECT YEAR(os.SALES_DATE) YEAR, MONTH(os.SALES_DATE) MONTH, GENDER GENDER, COUNT(DISTINCT ui.USER_ID) USERS
FROM USER_INFO ui JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER
ORDER BY YEAR, MONTH, GENDER